# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    - r-cran-ncdf4
    - libgdal1-dev
    - gdal-bin
    - libproj-dev
    - proj-data
    - proj-bin
    - libgeos-dev

branches:
  only:
    - devel
    - master
