# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    - r-cran-ncdf4

branches:
  only:
    - devel
    - master
